#!/bin/sh
case $1 in
        configure) 
        :
	addgroup --system git
	adduser --system --home /var/lib/gogs --ingroup git --shell /bin/bash git 

	chown git.git /opt/gogs/custom/conf
	chown git.git /opt/gogs/data
	chown git.git /opt/gogs/log
	chown -R git.git /var/lib/gogs

	update-rc.d gogs start 2 3 4 5 
	/etc/init.d/gogs start
	;;
esac
